### ISSUE TITLE
Declaration of a Service Lifetime Scope in ServiceActivator

### ISSUE THREAD

**Issue by preardon** [BrighterCommand/Brighter#1560] opened 2021-05-25 10:12 UTC
At the Minute the Service Activator is an IHostedService CommandHandlers processing these messages cannot consume a Scoped Service without Injecting a ScopeFactory and creating a new scope inside my Handler

I would like Brighter to Declare a scope, the Real question is where
- If we declare a Scope in the pump around the dispatcher this would solve the issue however the scope would be shared Further down stream (i.e. for Events we handle in chain and this will share the scope between them)
- If we declare a Scope inside of the Command processor this would also solve the issue however it may be  a bit low down in the code

Any Thoughts guys?
@iancooper @holytshirt

**Comment by iancooper** [comment] 2021-05-25 10:55
We don't want to bake the IoC library into Brighter's Command Processor,. Dispatcher etc. That is a design decision and comes from this article by Mark Seeman: https://blog.ploeh.dk/2014/05/19/di-friendly-framework/ There was a *strong* design discussion with the ASP.NET team around some of their design decisions here, but those conversations mostly fell on deaf ears.

So we have effectively Create and Release, and we expect implementations of HandlerFactory to work with that i.e. you pass us an instance when we say Create and you can do as you will with it when we say Release.

Whilst we support plugging into HostBuilder, we don't want to bake in the ASP.NET scopes to Brighter's core. (It looks as though the new lightweight HTTP offering won't require their own IoC container).

I can take a look and see what we might be able to do, but one thing we don't want to do is put the ASP.NET DI mechanics for scoped services inside Brighter's engine. What would be better is to figure out a way to manually control lifetime via Create and Release that worked with ASP.NET's viral approach to this

**Comment by penderi** [comment] 2021-05-25 11:04
Mate this is awesome, thanks @iancooper.
I agree about Di being on the age - and rightly too  - in the framework. Adding direct DI scopes wouldn't follow the current design at all.
How ameniable are you to an optional/confgurable IScopeFactory being added to the MessagePump? (I *think* that's the right level... ). We can then provide NoOp version and a version in the DI package that plugs into MS DI - when used it will wrap the call to DispatchRequest in a new DI Scope. 

They key behaviour we need is that each consumed message is within a scope so that dwonscale scoped dependencies (hello EF Core) are shared amongst repositories. Without it we're having to referenec and use the scopefactory in our handlers.

Here's hoping I'm not missing

**Comment by iancooper** [comment] 2021-05-25 11:13
I know that lots of other OSS projects have hit the same issue with the whole scoped service problem. it's a nightmare created by the ASP.NET team.

We don't want this in the MessagePump, I don't think its the right level.

I think the answer is to do something similar to Quartz here: https://andrewlock.net/using-scoped-services-inside-a-quartz-net-hosted-service-with-asp-net-core/

Given we always call your factory to construct, I suspect the answer lies in the factory that you build the handler from doing so within the scope by getting the scope from which to find dependencies, and closing them out on release. 

It's possible that that we need to do something closer to quartz and effectively have a marker on your sink handler like [UseScopedServices] that means we don't instantiate your handler directly, but instantiate a scoped service handler, that in turn creates references scopefactory to create your handler and then passes the call t it. I'd prefer not to go there, because it's an ugly workaround to ASP.NET DI issues, but it is one route out if we need it.

**Comment by iancooper** [comment] 2021-05-25 11:18
There is also this alternative from the Quartz community to workaround this issue: https://gist.github.com/Antaris/9c3c097d31a90da279e3e6d78497a369

**Comment by iancooper** [comment] 2021-05-25 11:20
Given it may take a while for us to work this through, the gist use of a scope inside the factory may be the most solid approach to this for now

**Comment by penderi** [comment] 2021-05-25 11:22
Thanks mate - all helpful. Right now we're fugly - scopefactory in hadnelrs to new up dependencies (my face hasn't been pretty discussing this stuff). Factory seems a good shout. Great pointers

**Comment by iancooper** [comment] 2021-05-25 11:22
I know that Quartz has done something more long-lived now, but not had a chance to check on how they finally solved it, when looking at a long term choice: https://andrewlock.net/using-quartz-net-with-asp-net-core-and-worker-services/

**Comment by iancooper** [comment] 2021-05-25 11:27
@penderi I think one of those two strategies will be a better workaround. We may need to look at any 'factory' we create for you to see if we can implement the advice in the gist as otherwise I think we will default to a form that doesn't support scopes //cc @holytshirt 

I'll see what the quartz team did, I think that it might just be a marker to use a factory that supports scopes

**Comment by iancooper** [comment] 2021-05-25 11:39
This looks like what Quartz went with, similar to the gist above. They now default to it. It might be that we need to look at something similar with our default factory for use with ServiceCollection: https://github.com/quartznet/quartznet/blob/ecf1dd780e7feea85e34eb31a28b01bea27e82ae/src/Quartz.Extensions.DependencyInjection/Simpl/MicrosoftDependencyInjectionJobFactory.cs

**Comment by iancooper** [comment] 2021-05-25 11:40
(Without the property based approach though if possible)

**Comment by iancooper** [comment] 2021-05-25 11:41
For clarity, we would want to alter this: https://github.com/BrighterCommand/Brighter/blob/master/src/Paramore.Brighter.Extensions.DependencyInjection/ServiceProviderHandlerFactory.cs and the matching mapper factory as well for completeness

**Comment by preardon** [comment] 2021-05-25 13:40
@holytshirt Yeah the need is so that we can Share the EF DB Context between a few repositories in a scope and Rollback all Transactions if we need to

**Comment by iancooper** [comment] 2021-05-25 14:24
@holytshirt I think the way to go is to put a scope into our MS DI Container HandlerFactory implementation. Quartz.NET had to solve the same problem with scopes in their JobFactory

An original community approach to the problem: https://gist.github.com/Antaris/9c3c097d31a90da279e3e6d78497a369

Where they are today: https://github.com/quartznet/quartznet/blob/ecf1dd780e7feea85e34eb31a28b01bea27e82ae/src/Quartz.Extensions.DependencyInjection/Simpl/MicrosoftDependencyInjectionJobFactory.cs 

(But I don't think we want property injection)

**Comment by penderi** [comment] 2021-05-25 14:35
Don't flame me too hard... but what am I missing here ?

`
    public class ServiceProviderHandlerFactory : IAmAHandlerFactory, IAmAHandlerFactoryAsync
    {
        private readonly IServiceProvider _serviceProvider;

        public ServiceProviderHandlerFactory(IServiceProvider serviceProvider)
        {
            _serviceProvider = serviceProvider;
        }

        IHandleRequests IAmAHandlerFactory.Create(Type handlerType)
        {
            using (var scope = _serviceProvider.CreateScope())
            {
                return (IHandleRequests)scope.ServiceProvider.GetService(handlerType);
            }
        }

        IHandleRequestsAsync IAmAHandlerFactoryAsync.Create(Type handlerType)
        {
            using (var scope = _serviceProvider.CreateScope())
            {
                return (IHandleRequestsAsync)scope.ServiceProvider.GetService(handlerType);
            }
        }

        public void Release(IHandleRequests handler)
        {
            var disposal = handler as IDisposable;
            disposal?.Dispose();
        }

        public void Release(IHandleRequestsAsync handler)
        {
            var disposal = handler as IDisposable;
            disposal?.Dispose();
        }
    }
`
I'm presuming - we don't want the scope lasting more than the handler itself, we want to release the handler as before. The only smell for me is whether the lifetime of the scope itself (ie disposed from the using block) affects the lifetime of the depdency. If so then we need to track the scopes too and dispose on handler release.

**Comment by iancooper** [comment] 2021-05-25 14:44
@penderi The only difference here is the ability to dispose of the scope by tracking it: 

Original: https://gist.github.com/Antaris/9c3c097d31a90da279e3e6d78497a369
Improvement: https://github.com/AndyPook/QuartzHostedService/blob/master/QuartzHostedService/ScopedJobFactory.cs

**Comment by iancooper** [comment] 2021-05-25 14:45
@penderi So an equivalent for us would be to return a scoped handler that wraps the handler, and when disposed kills the scope itself.

**Comment by penderi** [comment] 2021-05-25 14:46
Yes @iancooper but I fear the problem is we can't identity the release for the individual request, only type. This could create an issue with overlapping handlers of the same type

**Comment by iancooper** [comment] 2021-05-25 14:51
@penderi I'd be happy with us providing an optional parameter on the HandleFactory methods that was the request id, so that we can disambiguate the request that the creation call is for. I think there are a lot of reasons why that could have value for us.

**Comment by penderi** [comment] 2021-05-25 14:52
This is almost like your at the desk lol. Yup saw that and reasoned could be useful. Very partial to using the context if it's not a misuse...?

**Comment by iancooper** [comment] 2021-05-25 14:52
@penderi But the wrapper approach of the second code sample might be a nicer approach overall

**Comment by penderi** [comment] 2021-05-25 15:02
Hmm wrapping with the generic handler looks like an unpleasant thing...

**Comment by iancooper** [comment] 2021-05-25 15:08
TBH if we wrap the scope with an class that implements IDispose we don't need to wrap the handler. Just set the HandlerScope property on the RequestHandler and in Release always remove if it is set. We can probably add the property to IAmAReqeustHandler, so it will always be there, just possibly null

**Comment by holytshirt** [comment] 2021-05-25 15:28
This should be for Service Activator only and not for Brighter. In aspnet core & EFcore the scope is created for you Brighter has to work with an already created scope. 
The advice we normal give people using aspnet core & EFcore  is to register the command processer as scoped 
https://github.com/BrighterCommand/todo-backend-aspnetcore-brighter/blob/master/src/ToDoApi/Startup.cs#L74-L75

**Comment by preardon** [comment] 2021-05-25 16:15
@holytshirt When I Register the Command Processor Lifetime as Scoped The Service Activator will not start as the iHostedService can't find the CommandProcessor

**Comment by holytshirt** [comment] 2021-05-25 16:21
@preardon that advice is not for Service Activator it's for when you are using Brighter in aspnet core with efcore.

**Comment by iancooper** [comment] 2021-05-25 16:22
@preardon I think @holytshirt's point is that we have two scenarios: ServiceActivator for a consumer receiving messages and stand-alone Brighter being used as a mediator. I guess his question is if we need to have two factories, one we use in ServiceActivator scenarios that creates a scope with the handler and one that we use in stand-alone scenarios, and configure accordingly.

**Comment by iancooper** [comment] 2021-05-25 16:24
@penderi You will want to test the scenario where we have a pipeline i.e. attributes with other handlers. Should anything created for that pipeline use the same scope? I guess if you wanted a DbContext in two handlers to be the same, the answer might be yes. That might move us toward a solution that crates an id for the pipeline

**Comment by iancooper** [comment] 2021-05-25 16:26
@holytshirt Just to note, Quartz originally had scoped and non-scoped and a flag to use scoped. They have now dropped that for scoped everywhere. Which is I guess a 'pit of success'. Any idea what the cost would be for scoped if you didn't need it?

**Comment by preardon** [comment] 2021-05-25 16:26
Ah, Sorry.  Yes this is only an issue on Service Activator, my apologies

**Comment by iancooper** [comment] 2021-05-25 16:40
@penderi All good, as long as we are light touch, and focus on abstractions i.e. you can implement the factories yourself if you are using a different IOC container, then we can touch core if we need to.

(I feel like Linus policing the kernel now)

**Comment by preardon** [comment] 2021-05-25 16:49
@holytshirt @iancooper I think if we have a ScopedFactory and the existing Factory and allow it configurable for Service Activator. I am currently working with @penderi to see if we can find an elegant way to do this, think we found something.

Thinking of passing in the ServiceProviderHandlerFactory to BuildCommandProcessor (Brighter.Extensions.DI) So that we can then Pass it in or build set it into BrighterHandlerBuilder (Called by both ServicaActivator.DI & Brighter.DI)

The question I have is do we to to pass in an option/HandlerFactory into BrighterHandlerBuilder or Add a "UseScopedHandlerFactory" flag to BrighterOptions?

This should keep the changes out of the Core of Brighter and around the Edges in much more Appropriate classes

**Comment by preardon** [comment] 2021-05-25 16:52
@iancooper Only just saw your above response, I suppose if we allow Passing into BrighterHandlerBuilder this will allow people to extend this to use any form of IoC they like

**Comment by iancooper** [comment] 2021-05-25 18:10
I would opt for: UseScopedHandlerFactory given the prior art by Quartz.NET

**Comment by preardon** [comment] 2021-06-02 14:43
@iancooper @holytshirt We will look to get a PR for this in at the back end of next week

**Comment by iancooper** [comment] 2021-08-19 09:57
@penderi Lots of movement around scopes, how does this fit in now?

**Comment by penderi** [comment] 2021-10-05 17:03
#1746 

@iancooper apologies for the delay. But at least I have something. Although I'm reticent. 

The best thing about this PR is it isolates the scope to what I think is the ideal esp for a worker - scope to an Event or Command received on by the Dispatcher. This is by creating the scope for each pipeline (in PipelineBuilder) - thereby covering all pre/post attributes and handlers.

I have *tried* to reduce concerns such as:
- reduce change to core interfaces
- keep scoped changes in service activator as much as possible
- keep it simple
- allow it to be extended

The are 2 real, well, turds to be frank:
- Use of IServiceScope in the core lib. I know I can adapt our way out of that so no biggie right now.
- The addition of lifetimeScope to *all* handler factories, but only used by Scoped

That last one could be mitigated by making a scope factory / DI aware but that starts snowballing change.

Comments awaited (dons helmet)

#1746

**Comment by iancooper** [comment] 2021-10-05 17:45
Thanks @penderi. I'll probably need a day or two to find time to review, and I have to look at a SNS/SQS issue first. Sorry. But if you can give me a few days I can look through and see where we are. Overall, we know that the ASP.NET Scope needs are painfully intrusive, but let's see what this does and if I can make any meaningful suggestions as to how we might limit the intrusion. In some cases just making the support optional in an assembly you pull in if you need it could work.

**Comment by iancooper** [comment] 2021-10-13 10:24
@penderi We fixed the requeue issues, so this is next up

**Comment by iancooper** [comment] 2021-12-12 22:07
Closing this one as done

**Closed** 2021-12-12 22:07 UTC
Labels: 3 - Done, Bug, v9
