### ISSUE TITLE
MySql Outbox - Issue with Connection Pooling

### ISSUE THREAD

**Issue by honkuan86** [BrighterCommand/Brighter#2077] opened 2022-04-18 04:31 UTC
### Describe the bug
When maxpoolsize property is set in MySql connection string, outbox sweeper will hit exception.
Tested with MySql Server 5.7.

### To Reproduce
Run any sample with MySql Outbox.

### Exceptions (if any)
MySqlConnector.MySqlException (0x80004005): Connect Timeout expired. All pooled connections are in use.
   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 940
   at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 445
   at MySqlConnector.MySqlConnection.Open() in /_/src/MySqlConnector/MySqlConnection.cs:line 369
   at Paramore.Brighter.Outbox.MySql.MySqlOutboxSync.OutstandingMessages(Double millSecondsSinceSent, Int32 pageSize, Int32 pageNumber, Dictionary`2 args) in /_/src/Paramore.Brighter.Outbox.MySql/MySqlOutboxSync.cs:line 351
   at Paramore.Brighter.OutboxSweeper.Sweep(Double milliSecondsSinceSent, IAmAnOutboxViewer`1 outbox, IAmACommandProcessor commandProcessor) in /_/src/Paramore.Brighter/OutboxSweeper.cs:line 38

Connection should be close after each operation is done.

**Comment by iancooper** [comment] 2022-05-24 08:34
We are going to close the issue for MySQL with #2106 , but either I or @preardon should review other providers. The issue is that when we finish with a connection we need to understand who owns it. If we do, we can close it, if we don't we can't and should leave it to whoever opened it to close it down.

Broadly if you look at #2106 you will see this needs a try...finally block that checks for ownership and closes if we own, and not a using statement

**Comment by honkuan86** [comment] 2022-06-27 03:21
Hi @iancooper, @holytshirt, @preardon , do you think we can release this fix by this week? because we are pending on this fix in one of our project and is releasing soon.

**Comment by preardon** [comment] 2022-06-27 18:21
@honkuan86 I should be able to get my parts out for you, and assuming @iancooper agrees I'll do a release

**Comment by holytshirt** [comment] 2022-06-28 16:15
If @iancooper is ready should be good to go

**Comment by preardon** [comment] 2022-06-28 18:31
I'm planning on getting the remaining fixes in tomorrow

**Comment by preardon** [comment] 2022-06-29 08:57
As Promised #2171

**Comment by preardon** [comment] 2022-07-01 10:26
@honkuan86 9.1.3 should be out, just wait for NuGet Cache

**Comment by iancooper** [comment] 2022-07-06 11:01
@preardon @honkuan86 Going to close this one

**Closed** 2022-07-06 11:01 UTC
Labels: 3 - Done, Bug
