### ISSUE TITLE
ASB - allow creating of topics/subscriptions to be optional

### ISSUE THREAD

**Issue by penderi** [BrighterCommand/Brighter#1444] opened 2021-03-18 17:01 UTC
**Is your feature request related to a problem? Please describe.**

Cloud hosting typically leaves infra concerns (topuic/subscription creation) to be outside of the scope of a component or service. Moreover reduced-rights deployment means attempts to create will fail.

Add the ability to ASB transport to only create topics and subscriptions when specified. Default = allow (as current)

mentioned in #1438

**Comment by preardon** [comment] 2021-03-18 18:43
@penderi @iancooper I'll have a PR in for this in ~30 minutes

**Comment by iancooper** [comment] 2021-03-18 18:56
@preardon Guessing you have seen the optional creation enum on the V9 publication and subscription?

**Comment by preardon** [comment] 2021-03-18 18:59
@iancooper I have not, I was just adding creation Booleans to AzureServiceBusConfiguration as I figured I would keep this confined to ASB Config. I can have a look to wire it up to the over arching config if you like

**Comment by iancooper** [comment] 2021-03-18 19:16
@preardon So on Subscription https://github.com/BrighterCommand/Brighter/blob/master/src/Paramore.Brighter/Subscription.cs and Publication https://github.com/BrighterCommand/Brighter/blob/master/src/Paramore.Brighter/Publication.cs we have an enum OnMissingChannels that indicates what you want us to do:

- Assume - don't validate or create, it's there trust me (low latency)
- Validate - check its there, if not raise a channel failure
- Create - create it

We assume for create producer creates channel (topic, routing key) but client creates queues etc.

That gets passed into your producer or consumer, and the code there has to do the work to determine what to do. When may vary. So with RMQ because it is a no-op if it exists and low-latency the Channel checks when it is called, but in AWS the ChannelFactory does it, not the Channel, because creation is high latency and we need to check if something exists before we create it.

So you have to think about where as well. I'm guessing that ASB is a REST API for creation, so it might make sense to look at the ChannelFactory in the same way AWS does

**Comment by iancooper** [comment] 2021-03-18 19:35
+ @penderi and @preardon Please make sure you are talking so we don't have two folks trying to fix the same issue :-D

**Comment by penderi** [comment] 2021-03-18 20:37
@iancooper don't worry @preardon is a mate at Flagstone, all good.

**Comment by holytshirt** [comment] 2021-03-19 00:31
Let me know if you happy to close this now @iancooper

**Comment by iancooper** [comment] 2021-03-19 09:17
@holytshirt Going to look shortly

**Comment by iancooper** [comment] 2021-03-19 09:41
@holytshirt I just wanted to check on the following. Forwarding my comments from the PR:

@preardon So the only thing that might be missing is that the consumer doesn't check for the topic and create it if asked to create. I don't know enough about the management wrapper to know if that will automatically check for the topic and create it, if it is missing, but it would probably need that if not. The consumer tends to check for everything - the producer only the topic.

**Comment by iancooper** [comment] 2021-03-19 09:42
If it subscription doesn't check for/auto-create the topic, we'll need a PR to fix that before we can close this issue.

**Comment by preardon** [comment] 2021-03-19 10:06
@iancooper I will have a look and report back

**Comment by preardon** [comment] 2021-03-19 12:06
@iancooper Have confirmed, does not AutoCreate Topic, PR Incoming

**Comment by preardon** [comment] 2021-03-27 21:53
Was doing some testing and found that I missed plumbing a part, PR incoming

**Comment by preardon** [comment] 2021-03-27 22:23
@iancooper Hey Mate, was looking deeper into this tonight, the error that ends up getting thrown on Channel Failure due to not Topic / Subscription Not existing ends up being "Could not receive message. Note that should return an MT_NONE from an empty queue on timeout" (MessagePump Line 89), Just wanted to get your opinion on this as while the original Error with reason gets swallowed, it'll be logged but there is no hint of the exact reason in the Final exception

**Comment by preardon** [comment] 2021-04-29 21:27
@iancooper I think we can close this

**Closed** 2021-04-30 08:27 UTC
Labels: 2 - In Progress, feature request
